export const environment = {
  production: false,
  apiKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjODcyNTc5OS1hYjJmLTQwZjYtOWNjMS04NTU0NWY3NGE0NzciLCJlbWFpbCI6ImZpbGlwZUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRmlsaXBlIiwibmJmIjoxNjk3MDQ0NTEyLCJleHAiOjE2OTcwNzMzMTIsImlhdCI6MTY5NzA0NDUxMiwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.gQXx8YrlVJDVnePhWT_qrPiPWBK2q7p3Jcu6w9mLVYs',
};
